table Current
	lineageTag: fa85ff54-e456-403d-809b-d4b78c96d4a3

	column 'location.name'
		dataType: string
		lineageTag: e2e1a643-9473-45d7-9c00-1b0478428af2
		summarizeBy: none
		sourceColumn: location.name

		annotation SummarizationSetBy = Automatic

	column 'location.region'
		dataType: string
		lineageTag: d5f64645-8b5d-4f9c-8660-5d6ef6c5fe0d
		summarizeBy: none
		sourceColumn: location.region

		annotation SummarizationSetBy = Automatic

	column 'location.country'
		dataType: string
		lineageTag: 09d97b1e-a431-4bfb-8a42-eafa7bf3da8c
		summarizeBy: none
		sourceColumn: location.country

		annotation SummarizationSetBy = Automatic

	column 'location.lat'
		dataType: double
		lineageTag: 957ab0fb-0dcf-46f1-aeac-18895003d895
		summarizeBy: sum
		sourceColumn: location.lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'location.lon'
		dataType: double
		lineageTag: 882d3297-f21f-404e-a7a4-e11efad58805
		summarizeBy: sum
		sourceColumn: location.lon

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'location.tz_id'
		dataType: string
		lineageTag: 7709058f-dce0-4a7e-8547-db135e2f93dc
		summarizeBy: none
		sourceColumn: location.tz_id

		annotation SummarizationSetBy = Automatic

	column 'location.localtime_epoch'
		dataType: int64
		formatString: 0
		lineageTag: a2cd6f27-06c2-47f2-9a80-98b9f8bb23c3
		summarizeBy: sum
		sourceColumn: location.localtime_epoch

		annotation SummarizationSetBy = Automatic

	column 'location.localtime'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5f656d81-b00c-4bc0-97e4-3292d5261bda
		summarizeBy: none
		sourceColumn: location.localtime

		variation Variation
			isDefault
			relationship: b7173895-8bfc-4300-b780-72686063dd37
			defaultHierarchy: LocalDateTable_0e9604a5-cb82-4dfd-8642-fc76f981ea8c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'current.last_updated_epoch'
		dataType: int64
		formatString: 0
		lineageTag: 8ab0354d-cea4-4135-ac9f-a697d4803761
		summarizeBy: sum
		sourceColumn: current.last_updated_epoch

		annotation SummarizationSetBy = Automatic

	column 'current.last_updated'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1a3c1b37-4603-42f7-85b5-56666ceac2bd
		summarizeBy: none
		sourceColumn: current.last_updated

		variation Variation
			isDefault
			relationship: e589ae9e-426a-4708-8c88-62a9a606dbc5
			defaultHierarchy: LocalDateTable_05718ad4-6996-43c4-9bcc-6c03eafe1c97.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'current.temp_c'
		dataType: double
		lineageTag: 6ab0a9f5-1c98-41fb-b25e-578fe1f2b05e
		summarizeBy: sum
		sourceColumn: current.temp_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.temp_f'
		dataType: double
		lineageTag: fada3849-23b3-49a8-9a7d-e25e0d724981
		summarizeBy: sum
		sourceColumn: current.temp_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.is_day'
		dataType: int64
		formatString: 0
		lineageTag: 66ea8c47-6c1b-4dc5-8949-9fe4c4d34e34
		summarizeBy: sum
		sourceColumn: current.is_day

		annotation SummarizationSetBy = Automatic

	column 'current.condition.text'
		dataType: string
		lineageTag: 225bbcb5-125e-4eee-b6d6-289bf31bd58c
		summarizeBy: none
		sourceColumn: current.condition.text

		annotation SummarizationSetBy = Automatic

	column 'current.condition.icon'
		dataType: string
		lineageTag: ef5d3fef-28b3-4047-b8b0-91db9bfaaeab
		summarizeBy: none
		sourceColumn: current.condition.icon

		annotation SummarizationSetBy = Automatic

	column 'current.condition.code'
		dataType: int64
		formatString: 0
		lineageTag: 0b992bdc-cf88-41d2-bff3-74bb09e60736
		summarizeBy: sum
		sourceColumn: current.condition.code

		annotation SummarizationSetBy = Automatic

	column 'current.wind_mph'
		dataType: double
		lineageTag: 6fa9d68a-3821-4ff1-829e-41fe784957dc
		summarizeBy: sum
		sourceColumn: current.wind_mph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.wind_kph'
		dataType: int64
		formatString: 0
		lineageTag: f58da295-b20c-40dd-95b0-87193a66e36e
		summarizeBy: sum
		sourceColumn: current.wind_kph

		annotation SummarizationSetBy = Automatic

	column 'current.wind_degree'
		dataType: int64
		formatString: 0
		lineageTag: c02b8887-0e19-41b9-98a7-2d6cb8cc7ee9
		summarizeBy: sum
		sourceColumn: current.wind_degree

		annotation SummarizationSetBy = Automatic

	column 'current.wind_dir'
		dataType: string
		lineageTag: e21233b7-b4c8-41c3-8c13-4120fb180ac0
		summarizeBy: none
		sourceColumn: current.wind_dir

		annotation SummarizationSetBy = Automatic

	column 'current.pressure_mb'
		dataType: int64
		formatString: 0
		lineageTag: 692fb90e-4c31-4364-9dc0-f93d98509515
		summarizeBy: sum
		sourceColumn: current.pressure_mb

		annotation SummarizationSetBy = Automatic

	column 'current.pressure_in'
		dataType: double
		lineageTag: cfde2db6-3b04-4e32-a728-c10e3579b66a
		summarizeBy: sum
		sourceColumn: current.pressure_in

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.precip_mm'
		dataType: double
		lineageTag: 928be8bd-a21b-4b95-84e0-da411e95a50f
		summarizeBy: sum
		sourceColumn: current.precip_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.precip_in'
		dataType: double
		lineageTag: 4868c289-79fa-48ae-9223-1f08500b6a68
		summarizeBy: sum
		sourceColumn: current.precip_in

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.humidity'
		dataType: int64
		formatString: 0
		lineageTag: 4ae413ec-eccf-4b3a-9c28-783364166e18
		summarizeBy: sum
		sourceColumn: current.humidity

		annotation SummarizationSetBy = Automatic

	column 'current.cloud'
		dataType: int64
		formatString: 0
		lineageTag: 12c00b9b-7de4-4329-a80e-e50a3f03028f
		summarizeBy: sum
		sourceColumn: current.cloud

		annotation SummarizationSetBy = Automatic

	column 'current.feelslike_c'
		dataType: double
		lineageTag: 65b32a29-0769-45d3-af0f-d8e3e46bf57a
		summarizeBy: sum
		sourceColumn: current.feelslike_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.feelslike_f'
		dataType: double
		lineageTag: a7ee1e3f-c1ae-4f0b-8fc8-695d262610c4
		summarizeBy: sum
		sourceColumn: current.feelslike_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.windchill_c'
		dataType: double
		lineageTag: e0c03f9e-a56c-4e33-95d5-824124fbdcc7
		summarizeBy: sum
		sourceColumn: current.windchill_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.windchill_f'
		dataType: double
		lineageTag: c060c87f-a637-4c80-8e58-9803f6352dcd
		summarizeBy: sum
		sourceColumn: current.windchill_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.heatindex_c'
		dataType: double
		lineageTag: 33ff9735-77ae-43ae-93c4-2f384231c5e8
		summarizeBy: sum
		sourceColumn: current.heatindex_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.heatindex_f'
		dataType: double
		lineageTag: 24ca3f00-6bf4-4d2c-ad65-3a6e26172d3f
		summarizeBy: sum
		sourceColumn: current.heatindex_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.dewpoint_c'
		dataType: double
		lineageTag: 63401d5b-fe5d-4f31-a960-5dba09fc1bd4
		summarizeBy: sum
		sourceColumn: current.dewpoint_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.dewpoint_f'
		dataType: double
		lineageTag: 4181f6f9-63d7-4bc3-b88b-8222e1249a81
		summarizeBy: sum
		sourceColumn: current.dewpoint_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.vis_km'
		dataType: int64
		formatString: 0
		lineageTag: 786b2f2e-c711-482b-abc6-1e8b0620906e
		summarizeBy: sum
		sourceColumn: current.vis_km

		annotation SummarizationSetBy = Automatic

	column 'current.vis_miles'
		dataType: int64
		formatString: 0
		lineageTag: 263ac8dc-0f22-4679-b3e8-9b372ce66176
		summarizeBy: sum
		sourceColumn: current.vis_miles

		annotation SummarizationSetBy = Automatic

	column 'current.uv'
		dataType: double
		lineageTag: a5415153-ec12-43b1-ba4c-caed462f3be1
		summarizeBy: sum
		sourceColumn: current.uv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.gust_mph'
		dataType: double
		lineageTag: a789ee0b-946d-45d5-964b-6a6dcc21255d
		summarizeBy: sum
		sourceColumn: current.gust_mph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.gust_kph'
		dataType: double
		lineageTag: 83e1c4d2-c6ff-4b81-8701-a07a2a9be236
		summarizeBy: sum
		sourceColumn: current.gust_kph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.air_quality.co'
		dataType: double
		lineageTag: 78c0e012-d741-4a67-8f98-759ec24b7a22
		summarizeBy: sum
		sourceColumn: current.air_quality.co

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.air_quality.no2'
		dataType: double
		lineageTag: e1721d45-bf16-4c53-92cf-ee138991913e
		summarizeBy: sum
		sourceColumn: current.air_quality.no2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.air_quality.o3'
		dataType: int64
		formatString: 0
		lineageTag: fdcf1bc2-8c4a-4cd9-bcf0-c15f19196448
		summarizeBy: sum
		sourceColumn: current.air_quality.o3

		annotation SummarizationSetBy = Automatic

	column 'current.air_quality.so2'
		dataType: double
		lineageTag: 6b06abad-f957-49a6-805b-b7bd8f50bc8d
		summarizeBy: sum
		sourceColumn: current.air_quality.so2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.air_quality.pm2_5'
		dataType: double
		lineageTag: 298d257d-799b-45c9-9e6d-85a572f34fc5
		summarizeBy: sum
		sourceColumn: current.air_quality.pm2_5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'current.air_quality.pm10'
		dataType: int64
		formatString: 0
		lineageTag: 2a82e593-0637-4690-8796-95dfe5b6f03d
		summarizeBy: sum
		sourceColumn: current.air_quality.pm10

		annotation SummarizationSetBy = Automatic

	column 'current.air_quality.us-epa-index'
		dataType: int64
		formatString: 0
		lineageTag: 51cc27cd-ef9d-4a7f-ac96-f3072c6d9a37
		summarizeBy: sum
		sourceColumn: current.air_quality.us-epa-index

		annotation SummarizationSetBy = Automatic

	column 'current.air_quality.gb-defra-index'
		dataType: int64
		formatString: 0
		lineageTag: 32a63d27-2968-4a35-b355-17353941f55f
		summarizeBy: sum
		sourceColumn: current.air_quality.gb-defra-index

		annotation SummarizationSetBy = Automatic

	partition Current = m
		mode: import
		source =
				let
				    Source = All_Weather,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"forecast.forecastday.date", "forecast.forecastday.date_epoch", "forecast.forecastday.day.maxtemp_c", "forecast.forecastday.day.maxtemp_f", "forecast.forecastday.day.mintemp_c", "forecast.forecastday.day.mintemp_f", "forecast.forecastday.day.avgtemp_c", "forecast.forecastday.day.avgtemp_f", "forecast.forecastday.day.maxwind_mph", "forecast.forecastday.day.maxwind_kph", "forecast.forecastday.day.totalprecip_mm", "forecast.forecastday.day.totalprecip_in", "forecast.forecastday.day.totalsnow_cm", "forecast.forecastday.day.avgvis_km", "forecast.forecastday.day.avgvis_miles", "forecast.forecastday.day.avghumidity", "forecast.forecastday.day.daily_will_it_rain", "forecast.forecastday.day.daily_chance_of_rain", "forecast.forecastday.day.daily_will_it_snow", "forecast.forecastday.day.daily_chance_of_snow", "forecast.forecastday.day.condition.text", "forecast.forecastday.day.condition.icon", "forecast.forecastday.day.condition.code", "forecast.forecastday.day.uv", "forecast.forecastday.day.air_quality.co", "forecast.forecastday.day.air_quality.no2", "forecast.forecastday.day.air_quality.o3", "forecast.forecastday.day.air_quality.so2", "forecast.forecastday.day.air_quality.pm2_5", "forecast.forecastday.day.air_quality.pm10", "forecast.forecastday.day.air_quality.us-epa-index", "forecast.forecastday.day.air_quality.gb-defra-index", "forecast.forecastday.day.air_quality.aqi_data", "forecast.forecastday.astro.sunrise", "forecast.forecastday.astro.sunset", "forecast.forecastday.astro.moonrise", "forecast.forecastday.astro.moonset", "forecast.forecastday.astro.moon_phase", "forecast.forecastday.astro.moon_illumination", "forecast.forecastday.astro.is_moon_up", "forecast.forecastday.astro.is_sun_up", "forecast.forecastday.hour.time_epoch", "forecast.forecastday.hour.time", "forecast.forecastday.hour.temp_c", "forecast.forecastday.hour.temp_f", "forecast.forecastday.hour.is_day", "forecast.forecastday.hour.condition.text", "forecast.forecastday.hour.condition.icon", "forecast.forecastday.hour.condition.code", "forecast.forecastday.hour.wind_mph", "forecast.forecastday.hour.wind_kph", "forecast.forecastday.hour.wind_degree", "forecast.forecastday.hour.wind_dir", "forecast.forecastday.hour.pressure_mb", "forecast.forecastday.hour.pressure_in", "forecast.forecastday.hour.precip_mm", "forecast.forecastday.hour.precip_in", "forecast.forecastday.hour.snow_cm", "forecast.forecastday.hour.humidity", "forecast.forecastday.hour.cloud", "forecast.forecastday.hour.feelslike_c", "forecast.forecastday.hour.feelslike_f", "forecast.forecastday.hour.windchill_c", "forecast.forecastday.hour.windchill_f", "forecast.forecastday.hour.heatindex_c", "forecast.forecastday.hour.heatindex_f", "forecast.forecastday.hour.dewpoint_c", "forecast.forecastday.hour.dewpoint_f", "forecast.forecastday.hour.will_it_rain", "forecast.forecastday.hour.chance_of_rain", "forecast.forecastday.hour.will_it_snow", "forecast.forecastday.hour.chance_of_snow", "forecast.forecastday.hour.vis_km", "forecast.forecastday.hour.vis_miles", "forecast.forecastday.hour.gust_mph", "forecast.forecastday.hour.gust_kph", "forecast.forecastday.hour.uv", "forecast.forecastday.hour.air_quality.co", "forecast.forecastday.hour.air_quality.no2", "forecast.forecastday.hour.air_quality.o3", "forecast.forecastday.hour.air_quality.so2", "forecast.forecastday.hour.air_quality.pm2_5", "forecast.forecastday.hour.air_quality.pm10", "forecast.forecastday.hour.air_quality.us-epa-index", "forecast.forecastday.hour.air_quality.gb-defra-index"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Duplicates","//","https://",Replacer.ReplaceText,{"current.condition.icon"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

