table Forecast_hour
	lineageTag: 8e7f6534-9f90-4af1-9230-d06cb5ccc6ec

	column 'location.name'
		dataType: string
		lineageTag: 97a49f3c-8b50-4449-9e08-96a63abd03a6
		summarizeBy: none
		sourceColumn: location.name

		annotation SummarizationSetBy = Automatic

	column 'location.region'
		dataType: string
		lineageTag: 562851cc-5ac5-429b-a573-00fb0ad9b904
		summarizeBy: none
		sourceColumn: location.region

		annotation SummarizationSetBy = Automatic

	column 'location.country'
		dataType: string
		lineageTag: e6f697af-a122-4029-8aa7-30a6ba41a8cb
		summarizeBy: none
		sourceColumn: location.country

		annotation SummarizationSetBy = Automatic

	column 'location.lat'
		dataType: double
		lineageTag: 821f86ae-c799-4e13-ace0-86a153b72120
		summarizeBy: sum
		sourceColumn: location.lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'location.lon'
		dataType: double
		lineageTag: 40731faf-ac08-41d3-af74-b4c528bd7195
		summarizeBy: sum
		sourceColumn: location.lon

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'location.tz_id'
		dataType: string
		lineageTag: 9066600b-b8f3-4044-90eb-5aca642d50a9
		summarizeBy: none
		sourceColumn: location.tz_id

		annotation SummarizationSetBy = Automatic

	column 'location.localtime_epoch'
		dataType: int64
		formatString: 0
		lineageTag: 64589421-ecb8-45a9-b36f-8444d5237135
		summarizeBy: sum
		sourceColumn: location.localtime_epoch

		annotation SummarizationSetBy = Automatic

	column 'location.localtime'
		dataType: dateTime
		formatString: General Date
		lineageTag: 3854874a-47a0-4554-83ed-718a07da6260
		summarizeBy: none
		sourceColumn: location.localtime

		variation Variation
			isDefault
			relationship: 73c75e4e-1c7c-4853-bd06-c13f82c2067a
			defaultHierarchy: LocalDateTable_d90a8a66-03c2-4b18-bd88-67422c09b0c3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.time_epoch'
		dataType: int64
		formatString: 0
		lineageTag: ed0c854f-a180-49c9-a893-fb47bd5d72b8
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.time_epoch

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.time'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0487bd2b-cc8b-4f2a-8e5d-9bf4e2f1de4d
		summarizeBy: none
		sourceColumn: forecast.forecastday.hour.time

		variation Variation
			isDefault
			relationship: 6a3b037e-05c6-4deb-b44b-ca3ebb5750db
			defaultHierarchy: LocalDateTable_bf6eb77f-7fe1-472e-97ae-40b1818ce534.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.temp_c'
		dataType: double
		lineageTag: 9f942640-9314-4125-90dc-791d402e64d0
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.temp_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.temp_f'
		dataType: double
		lineageTag: 8b27f876-2142-4a42-90c8-60fb9847d7cf
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.temp_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.is_day'
		dataType: int64
		formatString: 0
		lineageTag: 68edb44f-e00e-413d-bc7b-8adcf35f8c92
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.is_day

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.condition.text'
		dataType: string
		lineageTag: 7e5e8778-9053-4865-b834-ce91fcba4b49
		summarizeBy: none
		sourceColumn: forecast.forecastday.hour.condition.text

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.condition.icon'
		dataType: string
		lineageTag: 27741f94-550c-4cb8-aeda-b4a8f7d8f3d4
		summarizeBy: none
		sourceColumn: forecast.forecastday.hour.condition.icon

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.condition.code'
		dataType: int64
		formatString: 0
		lineageTag: a0afb8e0-81de-4225-9da9-895b1457a210
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.condition.code

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.wind_mph'
		dataType: double
		lineageTag: e5d6e5c2-8eb4-467c-8eed-9df58d1cc7d7
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.wind_mph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.wind_kph'
		dataType: double
		lineageTag: 4adfeb9e-3aec-462f-bfcd-08be1ad07e7c
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.wind_kph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.wind_degree'
		dataType: int64
		formatString: 0
		lineageTag: 5d77c63a-5db0-425d-ba5c-978bc54a6a04
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.wind_degree

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.wind_dir'
		dataType: string
		lineageTag: d9d14902-ed7d-4df4-a505-fde7e37e3522
		summarizeBy: none
		sourceColumn: forecast.forecastday.hour.wind_dir

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.pressure_mb'
		dataType: int64
		formatString: 0
		lineageTag: f5726092-5b1c-400d-bef2-21d7078626b3
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.pressure_mb

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.pressure_in'
		dataType: double
		lineageTag: 83f3669d-5c55-4b1d-8971-0199516bd795
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.pressure_in

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.precip_mm'
		dataType: double
		lineageTag: 7f29036e-0fb6-4556-b0f2-8d958fad3fc1
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.precip_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.precip_in'
		dataType: double
		lineageTag: b620a581-89f1-4c5d-957a-e78c2e7c3acb
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.precip_in

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.snow_cm'
		dataType: int64
		formatString: 0
		lineageTag: 2971a03f-5929-436f-bdff-b57cde912f78
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.snow_cm

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.humidity'
		dataType: int64
		formatString: 0
		lineageTag: c0922745-e3ab-4182-8d10-010e34ed44ee
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.humidity

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.cloud'
		dataType: int64
		formatString: 0
		lineageTag: 95f2ee91-60e3-4b2e-9cc9-1d97dd22a531
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.cloud

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.feelslike_c'
		dataType: double
		lineageTag: e0a6046f-3080-4257-8950-9fd4e196fc80
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.feelslike_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.feelslike_f'
		dataType: double
		lineageTag: 3e2339e3-6d44-40f4-bd50-9a2d99898e1b
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.feelslike_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.windchill_c'
		dataType: double
		lineageTag: 6d9fbcbd-8c98-4d3f-8ec8-32c512858637
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.windchill_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.windchill_f'
		dataType: double
		lineageTag: 61bd0002-5238-4a98-9ab5-a1e2ebb7eb85
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.windchill_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.heatindex_c'
		dataType: double
		lineageTag: 7beeade0-8304-4644-9770-0c5950014cae
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.heatindex_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.heatindex_f'
		dataType: double
		lineageTag: db2135c3-e597-4bb8-9233-d41aaf9b3a9d
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.heatindex_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.dewpoint_c'
		dataType: double
		lineageTag: b0f2149d-5611-40ef-bc63-106961f7538e
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.dewpoint_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.dewpoint_f'
		dataType: double
		lineageTag: f1e4fbdb-486d-4e6d-ba31-5c45b58dcea7
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.dewpoint_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.will_it_rain'
		dataType: int64
		formatString: 0
		lineageTag: 7d285788-f578-4a2f-976d-adeb412780ba
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.will_it_rain

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.chance_of_rain'
		dataType: int64
		formatString: 0
		lineageTag: 5946d3e5-f435-4696-b578-7b738beb1e86
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.chance_of_rain

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.will_it_snow'
		dataType: int64
		formatString: 0
		lineageTag: e8305eea-afbf-4522-b7c9-03f56f5ac410
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.will_it_snow

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.chance_of_snow'
		dataType: int64
		formatString: 0
		lineageTag: d49aac5f-5f8f-4f05-b41c-96d1f3a6ac78
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.chance_of_snow

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.vis_km'
		dataType: int64
		formatString: 0
		lineageTag: 49dee280-42f6-4592-afe9-e829aaf4610e
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.vis_km

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.vis_miles'
		dataType: int64
		formatString: 0
		lineageTag: 1c023896-2110-40e6-9e95-aa37551711d6
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.vis_miles

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.gust_mph'
		dataType: double
		lineageTag: 17068ae6-acbf-449c-8471-950219275abc
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.gust_mph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.gust_kph'
		dataType: double
		lineageTag: c33180da-8cc6-494c-951a-f6a8bdc9ca39
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.gust_kph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.uv'
		dataType: double
		lineageTag: 5920dbcd-85ef-4b94-92ce-f3bb1328cddc
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.uv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.air_quality.co'
		dataType: double
		lineageTag: 9ba6fb35-fd63-4a57-90b5-dc0d34a4d5bc
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.co

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.air_quality.no2'
		dataType: double
		lineageTag: 809f4f8c-6daa-46ac-85b0-4d1d433451fa
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.no2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.air_quality.o3'
		dataType: int64
		formatString: 0
		lineageTag: d30bd6d4-0320-4542-a41d-a3574308671f
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.o3

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.air_quality.so2'
		dataType: double
		lineageTag: b5e8c71c-6621-4532-aa8e-86c4b71778bc
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.so2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.air_quality.pm2_5'
		dataType: double
		lineageTag: aae68046-0594-4371-90bd-4d553942a5c9
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.pm2_5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.air_quality.pm10'
		dataType: double
		lineageTag: e3ae97e5-964b-46a7-985c-6ab5ab630842
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.pm10

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.hour.air_quality.us-epa-index'
		dataType: int64
		formatString: 0
		lineageTag: 544c4506-944c-49e0-a26f-afc9e67f1136
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.us-epa-index

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.hour.air_quality.gb-defra-index'
		dataType: int64
		formatString: 0
		lineageTag: e9a40fd8-c51e-4b87-abf8-2daefd8c4568
		summarizeBy: sum
		sourceColumn: forecast.forecastday.hour.air_quality.gb-defra-index

		annotation SummarizationSetBy = Automatic

	partition Forecast_hour = m
		mode: import
		source =
				let
				    Source = All_Weather,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"current.last_updated_epoch", "current.last_updated", "current.temp_c", "current.temp_f", "current.is_day", "current.condition.text", "current.condition.icon", "current.condition.code", "current.wind_mph", "current.wind_kph", "current.wind_degree", "current.wind_dir", "current.pressure_mb", "current.pressure_in", "current.precip_mm", "current.precip_in", "current.humidity", "current.cloud", "current.feelslike_c", "current.feelslike_f", "current.windchill_c", "current.windchill_f", "current.heatindex_c", "current.heatindex_f", "current.dewpoint_c", "current.dewpoint_f", "current.vis_km", "current.vis_miles", "current.uv", "current.gust_mph", "current.gust_kph", "current.air_quality.co", "current.air_quality.no2", "current.air_quality.o3", "current.air_quality.so2", "current.air_quality.pm2_5", "current.air_quality.pm10", "current.air_quality.us-epa-index", "current.air_quality.gb-defra-index", "forecast.forecastday.date", "forecast.forecastday.date_epoch", "forecast.forecastday.day.maxtemp_c", "forecast.forecastday.day.maxtemp_f", "forecast.forecastday.day.mintemp_c", "forecast.forecastday.day.mintemp_f", "forecast.forecastday.day.avgtemp_c", "forecast.forecastday.day.avgtemp_f", "forecast.forecastday.day.maxwind_mph", "forecast.forecastday.day.maxwind_kph", "forecast.forecastday.day.totalprecip_mm", "forecast.forecastday.day.totalprecip_in", "forecast.forecastday.day.totalsnow_cm", "forecast.forecastday.day.avgvis_km", "forecast.forecastday.day.avgvis_miles", "forecast.forecastday.day.avghumidity", "forecast.forecastday.day.daily_will_it_rain", "forecast.forecastday.day.daily_chance_of_rain", "forecast.forecastday.day.daily_will_it_snow", "forecast.forecastday.day.daily_chance_of_snow", "forecast.forecastday.day.condition.text", "forecast.forecastday.day.condition.icon", "forecast.forecastday.day.condition.code", "forecast.forecastday.day.uv", "forecast.forecastday.day.air_quality.co", "forecast.forecastday.day.air_quality.no2", "forecast.forecastday.day.air_quality.o3", "forecast.forecastday.day.air_quality.so2", "forecast.forecastday.day.air_quality.pm2_5", "forecast.forecastday.day.air_quality.pm10", "forecast.forecastday.day.air_quality.us-epa-index", "forecast.forecastday.day.air_quality.gb-defra-index", "forecast.forecastday.day.air_quality.aqi_data", "forecast.forecastday.astro.sunrise", "forecast.forecastday.astro.sunset", "forecast.forecastday.astro.moonrise", "forecast.forecastday.astro.moonset", "forecast.forecastday.astro.moon_phase", "forecast.forecastday.astro.moon_illumination", "forecast.forecastday.astro.is_moon_up", "forecast.forecastday.astro.is_sun_up"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Duplicates","//","https://",Replacer.ReplaceText,{"forecast.forecastday.hour.condition.icon"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

