table Forecast_days
	lineageTag: 1b16342c-e675-4a19-b287-932464889be0

	column 'location.name'
		dataType: string
		lineageTag: 4180e783-7028-46a3-b9c3-b6fcf34762fd
		summarizeBy: none
		sourceColumn: location.name

		annotation SummarizationSetBy = Automatic

	column 'location.region'
		dataType: string
		lineageTag: 6a1da8a4-fb97-4502-9940-0378db391e98
		summarizeBy: none
		sourceColumn: location.region

		annotation SummarizationSetBy = Automatic

	column 'location.country'
		dataType: string
		lineageTag: 7546652e-b2c9-427c-99a9-8b7e6c2403bf
		summarizeBy: none
		sourceColumn: location.country

		annotation SummarizationSetBy = Automatic

	column 'location.lat'
		dataType: double
		lineageTag: 2907f799-8c28-4035-b778-9bff1a6e4a2b
		summarizeBy: sum
		sourceColumn: location.lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'location.lon'
		dataType: double
		lineageTag: 51b0d38d-315f-46cd-9773-4d5408db9d59
		summarizeBy: sum
		sourceColumn: location.lon

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'location.tz_id'
		dataType: string
		lineageTag: b22e7eaf-ff97-44c7-8ded-156069976033
		summarizeBy: none
		sourceColumn: location.tz_id

		annotation SummarizationSetBy = Automatic

	column 'location.localtime_epoch'
		dataType: int64
		formatString: 0
		lineageTag: 126ce1a1-41d1-4e2c-a22c-afef8fb2ba79
		summarizeBy: sum
		sourceColumn: location.localtime_epoch

		annotation SummarizationSetBy = Automatic

	column 'location.localtime'
		dataType: dateTime
		formatString: General Date
		lineageTag: daabbb51-4d2b-4484-b22d-c29fde2a2bc0
		summarizeBy: none
		sourceColumn: location.localtime

		variation Variation
			isDefault
			relationship: e08da79f-8fba-4172-a1f4-c7a50e9fa60e
			defaultHierarchy: LocalDateTable_d58df626-6818-41dc-a468-6bd8ab881cb6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: db484cb0-c478-4fd9-815b-bdcd0c20d60f
		summarizeBy: none
		sourceColumn: forecast.forecastday.date

		variation Variation
			isDefault
			relationship: 07f33e28-260c-4194-8d7b-6d3d3c3001d0
			defaultHierarchy: LocalDateTable_01825919-d56f-4aea-a8b7-324b8d11f5cb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'forecast.forecastday.date_epoch'
		dataType: int64
		formatString: 0
		lineageTag: 1a4c1cd1-1aef-4b09-a265-9b8e4f0ba11e
		summarizeBy: sum
		sourceColumn: forecast.forecastday.date_epoch

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.maxtemp_c'
		dataType: double
		lineageTag: eac0ad39-6118-44fc-998c-a614752d3c34
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.maxtemp_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.maxtemp_f'
		dataType: double
		lineageTag: 83653074-8ebd-41d4-a0f1-a66ef5c9f520
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.maxtemp_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.mintemp_c'
		dataType: double
		lineageTag: c7deac9c-6c35-4971-a785-ee0396b8adb3
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.mintemp_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.mintemp_f'
		dataType: double
		lineageTag: 7e22ad0e-e3af-463b-92a6-5215350bfd41
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.mintemp_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.avgtemp_c'
		dataType: double
		lineageTag: 0600363b-f5ff-4198-b038-94cf907accf3
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.avgtemp_c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.avgtemp_f'
		dataType: double
		lineageTag: 1fd19e95-bd3e-41cd-a722-576731f14c48
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.avgtemp_f

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.maxwind_mph'
		dataType: double
		lineageTag: a09a6494-92f7-4b58-921c-13f97a531b8b
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.maxwind_mph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.maxwind_kph'
		dataType: double
		lineageTag: 759d892a-6bba-4199-a65b-96c7effa268c
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.maxwind_kph

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.totalprecip_mm'
		dataType: double
		lineageTag: 2b591a73-6b00-4898-a705-8f16fb88e661
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.totalprecip_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.totalprecip_in'
		dataType: double
		lineageTag: f45459b1-cb38-43c9-bab2-6157248c5696
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.totalprecip_in

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.totalsnow_cm'
		dataType: int64
		formatString: 0
		lineageTag: 46fcc247-1919-49ef-b462-c294cded0b4b
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.totalsnow_cm

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.avgvis_km'
		dataType: double
		lineageTag: 24ca9d50-d113-47c7-81d6-eb5daa28fe8f
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.avgvis_km

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.avgvis_miles'
		dataType: int64
		formatString: 0
		lineageTag: b2ae3938-e1d6-4f19-908c-7b7661ac70f7
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.avgvis_miles

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.avghumidity'
		dataType: int64
		formatString: 0
		lineageTag: a8e0978f-b19e-47b8-849c-94555d3349a4
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.avghumidity

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.daily_will_it_rain'
		dataType: int64
		formatString: 0
		lineageTag: 68385931-2ade-4785-8083-b02a6d89e649
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.daily_will_it_rain

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.daily_chance_of_rain'
		dataType: int64
		formatString: 0
		lineageTag: 89a9c6c8-d97d-4e49-a5d3-c1c98497cc1b
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.daily_chance_of_rain

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.daily_will_it_snow'
		dataType: int64
		formatString: 0
		lineageTag: c4c13c9f-84d8-46e8-9095-00466bb8bf38
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.daily_will_it_snow

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.daily_chance_of_snow'
		dataType: int64
		formatString: 0
		lineageTag: fc5b3754-0b56-40f7-94c7-29b81dbbf0f6
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.daily_chance_of_snow

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.condition.text'
		dataType: string
		lineageTag: 3e998d5a-f959-4dd3-8284-59d473f4cea6
		summarizeBy: none
		sourceColumn: forecast.forecastday.day.condition.text

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.condition.icon'
		dataType: string
		lineageTag: 114276d7-4d47-46e8-bfbe-ebe853728a55
		summarizeBy: none
		sourceColumn: forecast.forecastday.day.condition.icon

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.condition.code'
		dataType: int64
		formatString: 0
		lineageTag: 1ecd1091-3aee-4409-b3bd-755dc4d139d2
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.condition.code

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.uv'
		dataType: double
		lineageTag: b7422239-cff3-49e8-a949-0be3c09dc9fa
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.uv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.air_quality.co'
		dataType: double
		lineageTag: 4afef338-9f76-47ed-b31a-829c9b2ca784
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.co

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.air_quality.no2'
		dataType: double
		lineageTag: aa51b28e-8255-4a68-aa1a-5b3a7ddb8fa5
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.no2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.air_quality.o3'
		dataType: double
		lineageTag: 54d5f16d-b0f7-46fd-a0ec-00781ff5a065
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.o3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.air_quality.so2'
		dataType: double
		lineageTag: decadf2d-0ca9-4224-a8bc-e5c424909cf8
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.so2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.air_quality.pm2_5'
		dataType: double
		lineageTag: dded9f2e-9091-4b2a-a7bc-72f9219ca226
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.pm2_5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.air_quality.pm10'
		dataType: double
		lineageTag: 7d03c924-e803-4360-b43b-4af12b216b8f
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.pm10

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'forecast.forecastday.day.air_quality.us-epa-index'
		dataType: int64
		formatString: 0
		lineageTag: 9b023f36-c369-4cce-b391-67472584f2f1
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.us-epa-index

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.air_quality.gb-defra-index'
		dataType: int64
		formatString: 0
		lineageTag: e6ff5636-02de-4740-afc8-c88d67e234dd
		summarizeBy: sum
		sourceColumn: forecast.forecastday.day.air_quality.gb-defra-index

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.day.air_quality.aqi_data'
		dataType: string
		lineageTag: 81e0fbb4-4350-4f58-90b9-c1299c9fd5ce
		summarizeBy: none
		sourceColumn: forecast.forecastday.day.air_quality.aqi_data

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.astro.sunrise'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 4133de22-f5e7-4129-91a9-c3d195641e9a
		summarizeBy: none
		sourceColumn: forecast.forecastday.astro.sunrise

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'forecast.forecastday.astro.sunset'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 54172b9f-a6be-4385-94fc-f4de2cdfd13a
		summarizeBy: none
		sourceColumn: forecast.forecastday.astro.sunset

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'forecast.forecastday.astro.moonrise'
		dataType: dateTime
		formatString: Long Time
		lineageTag: e8c325df-e658-4e67-bbe0-26a8d90ce7e5
		summarizeBy: none
		sourceColumn: forecast.forecastday.astro.moonrise

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'forecast.forecastday.astro.moonset'
		dataType: string
		lineageTag: 8e2080db-58d6-44f0-9e1a-61871e82acbf
		summarizeBy: none
		sourceColumn: forecast.forecastday.astro.moonset

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.astro.moon_phase'
		dataType: string
		lineageTag: a9969950-5bc7-4e72-8510-38ab23dea129
		summarizeBy: none
		sourceColumn: forecast.forecastday.astro.moon_phase

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.astro.moon_illumination'
		dataType: int64
		formatString: 0
		lineageTag: 547a2ccd-1036-40cf-a685-4678db563f48
		summarizeBy: sum
		sourceColumn: forecast.forecastday.astro.moon_illumination

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.astro.is_moon_up'
		dataType: int64
		formatString: 0
		lineageTag: cb821955-3fac-46ae-9fad-89332a12501a
		summarizeBy: sum
		sourceColumn: forecast.forecastday.astro.is_moon_up

		annotation SummarizationSetBy = Automatic

	column 'forecast.forecastday.astro.is_sun_up'
		dataType: int64
		formatString: 0
		lineageTag: 5c333052-d68b-439e-ab91-dd5ed477df5a
		summarizeBy: sum
		sourceColumn: forecast.forecastday.astro.is_sun_up

		annotation SummarizationSetBy = Automatic

	column Day_Name = format(Forecast_days[forecast.forecastday.date],"dddd")
		lineageTag: 163232cf-9460-4e64-b184-9759c613ac89
		summarizeBy: none
		sortByColumn: 'forecast.forecastday.date'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sunrise_Date = FORMAT(Forecast_days[forecast.forecastday.astro.sunrise], "hh:mm AM/PM")
		lineageTag: 276829c6-874f-446f-820e-f03f6d6f286e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Sunset_Date = FORMAT(Forecast_days[forecast.forecastday.astro.sunset], "hh:mm AM/PM")
		lineageTag: d6fd4e0c-ed87-4d0c-bd9b-190368545fa2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Forecast_days = m
		mode: import
		source =
				let
				    Source = All_Weather,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"current.last_updated_epoch", "current.last_updated", "current.temp_c", "current.temp_f", "current.is_day", "current.condition.text", "current.condition.icon", "current.condition.code", "current.wind_mph", "current.wind_kph", "current.wind_degree", "current.wind_dir", "current.pressure_mb", "current.pressure_in", "current.precip_mm", "current.precip_in", "current.humidity", "current.cloud", "current.feelslike_c", "current.feelslike_f", "current.windchill_c", "current.windchill_f", "current.heatindex_c", "current.heatindex_f", "current.dewpoint_c", "current.dewpoint_f", "current.vis_km", "current.vis_miles", "current.uv", "current.gust_mph", "current.gust_kph", "current.air_quality.co", "current.air_quality.no2", "current.air_quality.o3", "current.air_quality.so2", "current.air_quality.pm2_5", "current.air_quality.pm10", "current.air_quality.us-epa-index", "current.air_quality.gb-defra-index", "forecast.forecastday.hour.time_epoch", "forecast.forecastday.hour.time", "forecast.forecastday.hour.temp_c", "forecast.forecastday.hour.temp_f", "forecast.forecastday.hour.is_day", "forecast.forecastday.hour.condition.text", "forecast.forecastday.hour.condition.icon", "forecast.forecastday.hour.condition.code", "forecast.forecastday.hour.wind_mph", "forecast.forecastday.hour.wind_kph", "forecast.forecastday.hour.wind_degree", "forecast.forecastday.hour.wind_dir", "forecast.forecastday.hour.pressure_mb", "forecast.forecastday.hour.pressure_in", "forecast.forecastday.hour.precip_mm", "forecast.forecastday.hour.precip_in", "forecast.forecastday.hour.snow_cm", "forecast.forecastday.hour.humidity", "forecast.forecastday.hour.cloud", "forecast.forecastday.hour.feelslike_c", "forecast.forecastday.hour.feelslike_f", "forecast.forecastday.hour.windchill_c", "forecast.forecastday.hour.windchill_f", "forecast.forecastday.hour.heatindex_c", "forecast.forecastday.hour.heatindex_f", "forecast.forecastday.hour.dewpoint_c", "forecast.forecastday.hour.dewpoint_f", "forecast.forecastday.hour.will_it_rain", "forecast.forecastday.hour.chance_of_rain", "forecast.forecastday.hour.will_it_snow", "forecast.forecastday.hour.chance_of_snow", "forecast.forecastday.hour.vis_km", "forecast.forecastday.hour.vis_miles", "forecast.forecastday.hour.gust_mph", "forecast.forecastday.hour.gust_kph", "forecast.forecastday.hour.uv", "forecast.forecastday.hour.air_quality.co", "forecast.forecastday.hour.air_quality.no2", "forecast.forecastday.hour.air_quality.o3", "forecast.forecastday.hour.air_quality.so2", "forecast.forecastday.hour.air_quality.pm2_5", "forecast.forecastday.hour.air_quality.pm10", "forecast.forecastday.hour.air_quality.us-epa-index", "forecast.forecastday.hour.air_quality.gb-defra-index"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Duplicates","//","https://",Replacer.ReplaceText,{"forecast.forecastday.day.condition.icon"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

